version: '3.8'

services:
  # MongoDB: Servicio de base de datos compartida
  mongoservice:
    image: mongo:6.0
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=myuser
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
      - MONGO_INITDB_DATABASE=Login
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  # Backend 1: Instancia del back-end en el puerto 3001
  backend1:
    image: tu-usuario/todo-app:latest
    build: .
    ports:
      - "3001:5000"
    depends_on:
      - mongoservice
    environment:
      - MONGO_URI=mongodb://myuser:mypassword@mongoservice:27017/Login
      - INSTANCE_NAME=backend1

  backend2:
    image: tu-usuario/todo-app:latest
    build: .
    ports:
      - "3002:5000"
    depends_on:
      - mongoservice
    environment:
      - MONGO_URI=mongodb://myuser:mypassword@mongoservice:27017/Login
      - INSTANCE_NAME=backend2

  backend3:
    image: tu-usuario/todo-app:latest
    build: .
    ports:
      - "3003:5000"
    depends_on:
      - mongoservice
    environment:
      - MONGO_URI=mongodb://myuser:mypassword@mongoservice:27017/Login
      - INSTANCE_NAME=backend3

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend1
      - backend2
      - backend3
volumes:
  mongo-data:

