apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:8.0
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: myuser
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: mypassword
            - name: MONGO_INITDB_DATABASE
              value: Login
---
apiVersion: v1
kind: Service
metadata:
  name: mongoservice
spec:
  selector:
    app: mongodb
  ports:
    - port: 27017
      targetPort: 27017