apiVersion: apps/v1
kind: Deployment
metadata:
<<<<<<< HEAD:mongodb-deployment.yaml
  name: mongodb-deployment
=======
  name: mongodb
  labels:
    app: mongodb
>>>>>>> 84d098d54514db6d25d56a312f0791cfaae4cc15:mongo.yaml
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-password
<<<<<<< HEAD:mongodb-deployment.yaml
=======
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
>>>>>>> 84d098d54514db6d25d56a312f0791cfaae4cc15:mongo.yaml
