apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {}

    http {
      upstream backend {
        server backend-service:5000;
      }

      server {
        listen 80;

        location / {
          proxy_pass http://backend;
        }
      }
    }