apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80        # Puerto del servicio dentro del clúster
      targetPort: 8080  # Puerto del contenedor al que se dirige el tráfico
  type: ClusterIP
