# Imagen de tu aplicación
image:
  repository: juliogalaan/todo-app
  tag: latest

# Credenciales de MongoDB
mongodb:
  database: Login

# Configuración del Ingress
ingress:
  host: todo-app.local

resources:
  limits:
    memory: "512Mi"
    cpu: "500m"
  requests:
    memory: "256Mi"
    cpu: "250m"
env:
  MONGO_URI: "mongodb://todo-app-mongodb:27017/Login"
