apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-todo-backend
spec:
  # replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-todo-backend
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-todo-backend
    spec:
      containers:
        - name: todo-backend
          image: juliogalaan/todo-app
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_URI
              value: mongodb://myuser:mypassword@mi-todo-mongoservice:27017/Login


---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend-service
spec:
  type: NodePort
  selector:
    app: {{ .Release.Name }}-todo-backend
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 32000