apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-mongodb
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:8.0
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: {{ .Values.mongodb.username }}
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: {{ .Values.mongodb.password }}
            - name: MONGO_INITDB_DATABASE
              value: {{ .Values.mongodb.database }}
          ports:
            - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mongoservice
spec:
  selector:
    app: {{ .Release.Name }}-mongodb
  ports:
    - port: 27017
      targetPort: 27017