apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-nginx-config
data:
  nginx.conf: |
    events {}

    http {
      upstream backend_cluster {
        server {{ .Release.Name }}-backend-service:5000;
      }

      server {
        listen 80;

        location / {
          proxy_pass http://backend_cluster;
        }
      }
    }